apiVersion: apps/v1
kind: Deployment
metadata:
  name: veneer-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bigtable-veneer-client, java-bigtable
    spec:
      containers:
        - name: cos-channel-clr
          image: 'gcr.io/${google_cloud_project}/verify-bigtable:v4'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1.0"
            limits:
              cpu: "4"