apiVersion: svc/v1
kind: Service
metadata:
  name: veneer-clnt-svc
  labels:
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: veneer-app-deployment
  type: LoadBalancer