apiVersion: v1
kind: Pod
metadata:
  name: verify-bigtable
spec:
  containers:
    - name: bigtable-test-ctr
      image: gcr.io/grass-clump-479/verify-bigtable
      resources:
        requests:
          cpu: "4"
        limits:
          cpu: "4"