apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myapp-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-test
    spec:
      containers:
        - name: myapp-test
          image: 'gcr.io/${google_cloud_project}/verify-bigtable:v4'
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "4"
            limits:
              cpu: "4"

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-test-svc
  labels:
    name: myapp-test-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: myapp-test
  type: LoadBalancer
